print("Python has more than 70 excpetion handler !!!")
try:
    print("Inside try block")
    t1=()
    print("new tuple t1:",t1)
    print(t1[100])

except IndexError as ie:
    print("Fetched 100th element of t1")

except Exception as e:
    print("Exception: ",e)
finally:
    print(Exception)
    print(ArithmeticError)
    print(AssertionError)
    print(AttributeError)
    print(BaseException)
    print(BlockingIOError)
    print(BrokenPipeError)
    print(BufferError)
    print("#",BytesWarning)
    print(ChildProcessError)
    print(ConnectionAbortedError)
    print(ConnectionError)
    print(ConnectionRefusedError)
    print(ConnectionResetError)
    print("#",DeprecationWarning )
    print(EOFError)
    #print(Ellipsis)
    print(EnvironmentError)
    print(FileExistsError)
    print(FileNotFoundError)
    print(FloatingPointError)
    print("#",FutureWarning)
    print(GeneratorExit)
    print(IOError)
    print(ImportError)
    print("#",ImportWarning)
    print(IndentationError)
    print(IndexError)
    print(InterruptedError)
    print(IsADirectoryError)
    print(KeyError)
    print(KeyboardInterrupt)
    print(LookupError)
    print(MemoryError)
    print(NameError)
    print(NotADirectoryError)
    print("#",NotImplemented)
    print(NotImplementedError)
    print(OSError)
    print(OverflowError)
    print("#",PendingDeprecationWarning)
    print(PermissionError)
    print(ProcessLookupError)
    print(RecursionError)
    print(ReferenceError)
    print("#",ResourceWarning)
    print("#",StopAsyncIteration)
    print("#",StopIteration)
    print(SyntaxError)
    print(SyntaxWarning)
    print(SystemError)
    print("#",SystemExit)
    print(TabError)
    print(TimeoutError)
    print(TypeError)
    print(UnboundLocalError)
    print(UnicodeDecodeError)
    print(UnicodeEncodeError)
    print(UnicodeError)
    print(UnicodeTranslateError)
    print("#",UnicodeWarning)
    print("#",UserWarning)
    print(ValueError)
    print(WindowsError)
    print(ZeroDivisionError )
