#program for standard lib intro 
import string,textwrap
print("for PSL ,you can say 'batteries included' in python,more than 200 package and modules included in PSL")
print("\nString Handling")
print("RESULT OF <<<help(string)>>>")
print(help(string))
print("1>string module #path of string.py file:C:\Python34\Lib")
print("string.ChainMap >",string.ChainMap,"# for info type help(string.ChainMap)")
print("string.Formatter>",string.Formatter)
print("string.printable>",string.printable)
print("string.ascii_letters>",string.ascii_letters)
print("string.ascii_letters[14]>",string.ascii_letters[14])
print("string.ascii_lowercase>",string.ascii_lowercase)
print("string.ascii_uppercase>",string.ascii_uppercase)
print("string.Template>",string.Template)
print("help(string.capwords)>",help(string.capwords))
print("string.digits>",string.digits)
print("string.hexdigits>",string.hexdigits)
print("string.octdigits>",string.octdigits)
print("string.punctuation>",string.punctuation)
print("string.whitespace>",string.whitespace)
#print("2> textwrap")
