import sys,getopt
#print(sys)
print(sys.argv)
#print(getopt)
print(help(getopt))
print(sys.copyright)
print(sys.getdefaultencoding())
print(sys.getcheckinterval())
print(sys.getfilesystemencoding())
print(sys.getprofile())
print(sys.getwindowsversion())
print(sys.version)
print(sys.version_info)
ss= sys.stderr.write("This is sample string ")
print(type(ss))
print(ss)
